services:
  classifier:
    build: .
    container_name: llm-classifier
    restart: unless-stopped
    ports:
      - "9191:9191"
    volumes:
      - ollama_bind:/root/.ollama   # mounting the named volume (bind)
    environment:
      - OLLAMA_HOST=http://localhost:11434
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 8G

volumes:
  ollama_bind:
    driver: local
    driver_opts:
      type: none
      device: /opt/idol/idol-containers-toolkit/common-files/docker-volumes/classifier   # ruta de tu host (barras normales)
      o: bind